server:
  port: 80
eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
#    register-with-eureka: false
spring:
  application:
    name: consumer-dept-feign
feign:
  hystrix:
    enabled: true
#  client:
#    config:
#      MICROSERVICECLOUD-DEPT: #写default代表所有服务都设置超时时间
#        connectTimeout: 10000 #单位毫秒
#        readTimeout: 10000 #单位毫秒

#feigin日志增强功能
logging:
  level:
    com.atguigu.springcloud.service.DeptClientService: debug
#openfegin超时配置
#ribbon:
#  ReadTimeout: 5000
#  ConnectionTimeout: 5000