server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true #显示ip

info:
  app.name: atguigu-microservicecloud-zuul
  company.name: www.atguigu.com
  build.argifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: microservicecloud-zuul-gateway

zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /atguigu







